name: posts_app
description: "A Posts App Project"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc:
  flutter_bloc:
  cached_network_image:
  intl:
  dio:
  shared_preferences:
  flutter_secure_storage:
  equatable:
  skeletonizer:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Black_Han_Sans
      fonts:
        - asset: assets/fonts/Black_Han_Sans/BlackHanSans-Regular.ttf
          weight: 500
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700